"""initial

Revision ID: 0858598983f8
Revises: 
Create Date: 2026-02-08 23:03:15.764550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0858598983f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_roles_tenant_id'), 'auth_roles', ['tenant_id'], unique=False)
    op.create_table('auth_users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='userstatus'), nullable=False),
    sa.Column('role_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_tenant_id'), 'auth_users', ['tenant_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'overdue', 'paid', 'canceled', name='invoicestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_tenant_id'), 'billing_invoices', ['tenant_id'], unique=False)
    op.create_table('crm_clients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='clientstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_clients_tenant_id'), 'crm_clients', ['tenant_id'], unique=False)
    op.create_table('crm_leads',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'disqualified', 'converted', name='leadstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_tenant_id'), 'crm_leads', ['tenant_id'], unique=False)
    op.create_table('finance_accounts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'income', 'expense', name='accounttype'), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='accountstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_accounts_tenant_id'), 'finance_accounts', ['tenant_id'], unique=False)
    op.create_table('finance_companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('trading_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='companystatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_companies_tenant_id'), 'finance_companies', ['tenant_id'], unique=False)
    op.create_table('finance_payables',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'overdue', 'canceled', name='payablestatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_payables_tenant_id'), 'finance_payables', ['tenant_id'], unique=False)
    op.create_table('finance_payments',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('pix', 'card', 'bank_transfer', 'cash', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'canceled', name='paymentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_payments_tenant_id'), 'finance_payments', ['tenant_id'], unique=False)
    op.create_table('finance_receivables',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('source_domain', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'received', 'overdue', 'canceled', name='receivablestatus'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_receivables_tenant_id'), 'finance_receivables', ['tenant_id'], unique=False)
    op.create_table('hr_absences',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'justified', 'unexcused', name='absencestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_absences_tenant_id'), 'hr_absences', ['tenant_id'], unique=False)
    op.create_table('hr_benefits',
    sa.Column('type', sa.Enum('vr', 'va', 'vt', name='benefittype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'canceled', name='benefitstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_benefits_tenant_id'), 'hr_benefits', ['tenant_id'], unique=False)
    op.create_table('hr_candidates',
    sa.Column('recruitment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', name='candidatestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_candidates_tenant_id'), 'hr_candidates', ['tenant_id'], unique=False)
    op.create_table('hr_contracts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('clt', 'pj', 'intern', 'temp', name='contracttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'terminated', name='contractstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_contracts_tenant_id'), 'hr_contracts', ['tenant_id'], unique=False)
    op.create_table('hr_documents',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('medical_certificate', 'proof', 'contract', 'other', name='documenttype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_documents_tenant_id'), 'hr_documents', ['tenant_id'], unique=False)
    op.create_table('hr_employees',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=False),
    sa.Column('terminated_at', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='employeestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employees_tenant_id'), 'hr_employees', ['tenant_id'], unique=False)
    op.create_table('hr_leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'canceled', name='leaverequeststatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_leave_requests_tenant_id'), 'hr_leave_requests', ['tenant_id'], unique=False)
    op.create_table('hr_recruitments',
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'on_hold', 'closed', name='recruitmentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_recruitments_tenant_id'), 'hr_recruitments', ['tenant_id'], unique=False)
    op.create_table('hr_time_entries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('late', 'overtime', 'regular', name='timeentrytype'), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='timeentrystatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_time_entries_tenant_id'), 'hr_time_entries', ['tenant_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.Enum('unit', 'kg', 'g', 'l', 'ml', 'm', 'cm', name='itemunit'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='itemstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False)
    op.create_table('inventory_stock_adjustments',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_adjustments_tenant_id'), 'inventory_stock_adjustments', ['tenant_id'], unique=False)
    op.create_table('sales_opportunities',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('prospecting', 'proposal', 'negotiation', 'won', 'lost', name='opportunitystage'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_opportunities_tenant_id'), 'sales_opportunities', ['tenant_id'], unique=False)
    op.create_table('shared_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'restore', 'login', 'logout', 'password_change', 'stage_change', 'approve', 'reject', 'assign', 'convert', 'confirm', 'terminate', 'export', 'import_', 'activate_extension', 'deactivate_extension', name='auditaction'), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_audit_logs_actor_id'), 'shared_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_shared_audit_logs_tenant_id'), 'shared_audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_audit_logs_tenant_id'), table_name='shared_audit_logs')
    op.drop_index(op.f('ix_shared_audit_logs_actor_id'), table_name='shared_audit_logs')
    op.drop_table('shared_audit_logs')
    op.drop_index(op.f('ix_sales_opportunities_tenant_id'), table_name='sales_opportunities')
    op.drop_table('sales_opportunities')
    op.drop_index(op.f('ix_inventory_stock_adjustments_tenant_id'), table_name='inventory_stock_adjustments')
    op.drop_table('inventory_stock_adjustments')
    op.drop_index(op.f('ix_inventory_items_tenant_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_hr_time_entries_tenant_id'), table_name='hr_time_entries')
    op.drop_table('hr_time_entries')
    op.drop_index(op.f('ix_hr_recruitments_tenant_id'), table_name='hr_recruitments')
    op.drop_table('hr_recruitments')
    op.drop_index(op.f('ix_hr_leave_requests_tenant_id'), table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index(op.f('ix_hr_employees_tenant_id'), table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_index(op.f('ix_hr_documents_tenant_id'), table_name='hr_documents')
    op.drop_table('hr_documents')
    op.drop_index(op.f('ix_hr_contracts_tenant_id'), table_name='hr_contracts')
    op.drop_table('hr_contracts')
    op.drop_index(op.f('ix_hr_candidates_tenant_id'), table_name='hr_candidates')
    op.drop_table('hr_candidates')
    op.drop_index(op.f('ix_hr_benefits_tenant_id'), table_name='hr_benefits')
    op.drop_table('hr_benefits')
    op.drop_index(op.f('ix_hr_absences_tenant_id'), table_name='hr_absences')
    op.drop_table('hr_absences')
    op.drop_index(op.f('ix_finance_receivables_tenant_id'), table_name='finance_receivables')
    op.drop_table('finance_receivables')
    op.drop_index(op.f('ix_finance_payments_tenant_id'), table_name='finance_payments')
    op.drop_table('finance_payments')
    op.drop_index(op.f('ix_finance_payables_tenant_id'), table_name='finance_payables')
    op.drop_table('finance_payables')
    op.drop_index(op.f('ix_finance_companies_tenant_id'), table_name='finance_companies')
    op.drop_table('finance_companies')
    op.drop_index(op.f('ix_finance_accounts_tenant_id'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_index(op.f('ix_crm_leads_tenant_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_clients_tenant_id'), table_name='crm_clients')
    op.drop_table('crm_clients')
    op.drop_index(op.f('ix_billing_invoices_tenant_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_auth_users_tenant_id'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_roles_tenant_id'), table_name='auth_roles')
    op.drop_table('auth_roles')
    # ### end Alembic commands ###
